on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.zip
          unzip apache-jmeter-5.4.1.zip
          cd apache-jmeter-5.4.1/bin

      - name: Install Plugins (Optional)
        run: |
          # Replace with your plugin installation commands
          # Example:
          jmeter/bin/PluginsManagerCMD.sh --generate-csv results.csv --input-jtl results.jtl --plugin-type AggregateReport plugins+=("jpgc-cmd" "jpgc-synthesis" "jp@gc - Dummy Sampler")

      - name: Copy Test Files
        run: |
          cp your_test_plan.jmx jmeter/bin/

      - name: Run Test Plan
        run: |
          jmeter/bin/jmeter -n -t your_test_plan.jmx -l results.jtl

      - name: Upload Results (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: jmeter/bin/results*.csv
