on:
  push:
    branches: [ main ]

jobs:
  test-Jmeter-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.zip
          unzip apache-jmeter-5.4.1.zip
          cd apache-jmeter-5.4.1/bin
          
      - name: Check JMeter Installation Path
        run: |
          # Search for the jmeter executable in common locations
          JMETER_PATHS=(
              "/usr/share/apache-jmeter-5.4.1/bin/jmeter"
              "/usr/local/share/apache-jmeter-5.4.1/bin/jmeter"
              "./apache-jmeter-5.4.1/bin/jmeter"  # Replace with your custom path if applicable
            )

          # Iterate through potential paths and verify existence
          for path in "${JMETER_PATHS[@]}"; do
              if [[ -f "$path" ]]; then
                echo "JMeter found at: $path"
                exit 0  # Exit successfully if found
              fi
            done

            # If not found in any location, exit with an error
          echo "JMeter installation path not found. Please check your configuration."
          exit 1

      - name: Download and Install PluginsManagerCMD.sh (if higher than 5.3.0)
        run: |
              if [[ "5.4.1" > "5.3.0" ]]; then
                # curl -O https://jmeter-plugins.org/get/
                cd ./apache-jmeter-5.4.1/lib
                curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
              fi

      # - name: Install JMeter Plugin Manager using PluginsManagerCMD.sh
      #   run: |
      #           if [[ "5.4.1" > "5.3.0" ]]; then
      #             ./apache-jmeter-5.4.1/bin/PluginsManagerCMD.sh --install-command-line
      #           fi


      - name: Download and Install Plugin Manager (Optional)
        run: |
          # Download JAR (skip if Plugin Manager already installed)
          if [[ ! -f "./apache-jmeter-5.4.1/lib/ext/jmeter-plugins-manager-1.10.jar" ]]; then
            cd ./apache-jmeter-5.4.1/lib/ext
            curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar
          fi

          # Install Plugin Manager (requires `jmeter` directory)
          # ./apache-jmeter-5.4.1/bin/PluginsManagerCMD.sh -n -t jmeter/lib/ext/jmeter-plugins-manager-1.10.jar

      - name: Install jpgc-dummy Plugin
        run: |
          wget https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip
          unzip jpgc-dummy-0.4.zip
          ./apache-jmeter-5.4.1/bin/PluginsManagerCMD.sh install jpgc-dummy-0.4.jar

      - name: Copy Test Files
        run: |
          cp your_test_plan.jmx jmeter/bin/

      - name: Run Test Plan
        run: |
          jmeter/bin/jmeter -n -t jmeter/bin/your_test_plan.jmx -l results.jtl

      - name: Convert JTL to CSV
        run: |
          jmeter/bin/JMeterPluginsCMD --generate-csv results.csv --input-jtl results.jtl

      - name: Analyze "error %" column
        run: |
          awk -F, '{ if ($9 > 2) { print "Error percentage exceeds 2% for request: " $2 } }' results.csv > errors.txt

      - name: Upload Results (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.csv,errors.txt
