on:
  push:
    branches: [ main ]
     
jobs:
  test-Jmeter-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.zip
          unzip apache-jmeter-5.6.2.zip
          cd apache-jmeter-5.6.2/bin
          
      - name: Check JMeter Installation Path
        run: |
          # Search for the jmeter executable in common locations
          JMETER_PATHS=(
              "/usr/share/apache-jmeter-5.6.2/bin/jmeter"
              "/usr/local/share/apache-jmeter-5.6.2/bin/jmeter"
              "./apache-jmeter-5.6.2/bin/jmeter"  # Replace with your custom path if applicable
            )

          # Iterate through potential paths and verify existence
          for path in "${JMETER_PATHS[@]}"; do
              if [[ -f "$path" ]]; then
                echo "JMeter found at: $path"
                exit 0  # Exit successfully if found
              fi
            done

            # If not found in any location, exit with an error
          echo "JMeter installation path not found. Please check your configuration."
          exit 1

      - name: Download and Install cmdrunner-2.3.jar
        run: |
              if [[ "5.6.2" > "5.3.0" ]]; then
                # curl -O https://jmeter-plugins.org/get/
                cd ./apache-jmeter-5.6.2/lib
                curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar
                # cd ./apache-jmeter-5.6.2/lib
                curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar
              fi
              
      # - name: Check JMeter bin directory files
      #   run: |
      #     ls -l ./apache-jmeter-5.6.2/lib/
      #     echo "Next lib directory"
      

      - name: Download and Install Plugin Manager (Optional)
        run: |
          # Download JAR (skip if Plugin Manager already installed)
          if [[ ! -f "./apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar" ]]; then
            cd ./apache-jmeter-5.6.2/lib/ext
            curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar
            echo "plugin Manager installed successfully"
          fi

          # Install PluginManagerCMD
          # java -cp ./apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

      - name: Install JMeter Plugin Manager using PluginsManagerCMD.sh
        run: |
          java -cp ./apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
              # if [[ "5.6.2" > "5.3.0" ]]; then
              #    java -cp ./apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
              # fi
          echo "PluginsManagerCMD.sh installed successfullyy"
 
                
      - name: Check for JMeter PluginsManagerCMD.sh and cmdrunner2.2
        run: |
          # Replace placeholders with actual paths based on your environment
          file_path="./apache-jmeter-5.6.2/bin/PluginsManagerCMD.sh"
          file_path_cmdRunner="./apache-jmeter-5.6.2/lib/cmdrunner-2.3.jar"
          file_path_pluginManger="./apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar"
          file_path_cmdrunner="./apache-jmeter-5.6.2/lib/cmdrunner-2.2.jar"
      
          if [[ -f "$file_path_cmdrunner" ]]; then
            echo "JMeter cmdrunner found at $file_path_cmdrunner"
            # Add steps to install plugins, run tests, etc. (optional)
          else
            echo "JMeter PluginsManagerCMD not found at $file_path_cmdrunner"
            # Add steps to download or install the Plugins Manager (optional)
            # Install Plugin Manager (requires `jmeter` directory)
            # java -cp ./apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
          fi

           if [[ -f "$file_path_cmdRunner" ]]; then
            echo "JMeter cmdrunner Plugins Manager found at $file_path_cmdRunner"
            # Add steps to install plugins, run tests, etc. (optional)
          else
            echo "JMeter cmdrunner Plugins Manager not found at $file_path_cmdRunner"
            # Add steps to download or install the Plugins Manager (optional)
          fi

          if [[ -f "$file_path_pluginManger" ]]; then
            echo "JMeter Plugins Manager found at $file_path_pluginManger"
            # Add steps to install plugins, run tests, etc. (optional)
          else
            echo "JMeter Plugins Manager not found at $file_path_pluginManger"
            # Add steps to download or install the Plugins Manager (optional)       
          fi
       
      - name: Download jpgc-dummy Plugin
        run: |
          # wget https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip
          # unzip jpgc-dummy-0.4.zip
          # ./apache-jmeter-5.6.2/bin/PluginsManagerCMD.sh install jpgc-cmd
          # wget https://jmeter-plugins.org/files/packages/jpgc-cmd-2.2.zip
          # unzip jpgc-cmd-2.2.zip
          ./apache-jmeter-5.6.2/bin/PluginsManagerCMD.sh install jpgc-cmd
          echo "installation of plugin jpgc-cmd is complete"
          ./apache-jmeter-5.6.2/bin/PluginsManagerCMD.sh install jpgc-dummy
          echo "installation of plugin jpgc-dummy is complete"
          
      # - name: Check JMeter bin directory files
      #   run: |
          # ls -l ./apache-jmeter-5.6.2/bin/
          # echo "Next lib directory"
          # ls -l ./apache-jmeter-5.6.2/lib/
          # echo "Next lib directory"
      #     ls -l ./apache-jmeter-5.6.2/lib/ext/
      #     echo "Next lib-ext directory"
    
      - name: Copy Test Files to Jmeter bin folder
        run: |
          cp ./DemoTest.jmx ./apache-jmeter-5.6.2/bin/

      - name: Run Test Plan
        run: |
          ./apache-jmeter-5.6.2/bin/jmeter -n -t ./apache-jmeter-5.6.2/bin/DemoTest.jmx -l ./apache-jmeter-5.6.2/bin/results.jtl -o ./apache-jmeter-5.6.2/bin/results.csv

      # - name: Convert JTL to CSV
      #   run: |
      #     ./apache-jmeter-5.6.2/bin/JMeterPluginsCMD.sh --generate-csv results.csv --input-jtl results.jtl --plugin-type AggregateReport

      - name: Check for JMeter JMeterPluginsCMD.sh
        run: |
          # Replace placeholders with actual paths based on your environment
          file_path_results_csv="./apache-jmeter-5.6.2/bin/results.jtl"

           if [[ -f "$file_path_results_csv" ]]; then
            echo "JMeter CSV found at $file_path_results_csv"
            # Add steps to install plugins, run tests, etc. (optional)
          else
            echo "JMeter CSV not found at $file_path_results_csv"
            # Add steps to download or install the Plugins Manager (optional)
          fi
     

      - name: Analyze "error %" column
        run: |
          awk -F, '{ if ($9 > 2) { print "Error percentage exceeds 2% for request: " $2 } }' ./apache-jmeter-5.6.2/bin/results.csv > errors.txt

      # - name: Upload Results (Optional)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jmeter-results
      #     path: results.csv,errors.txt
